name: Paddy3118
date: '2009-04-10 17:31:28'
url: 'http://paddy3118.blogspot.com'
message: "Hi Andrej, \r\nIn your response #26 can you expand on why you think the acceptance of the definition of g to be \"crazy\"?\r\n\r\nI don't see it at first glance. as long as i is defined when g is called, their is no problem. Remember that Python is a dynamic language and it could be quite correct to change the global context in which g is run and supply a definition for i; or trap the resultant exception as part of a programs functionality. \r\n\r\nI find that if I have a problem with Python, then a calm post to comp.lang.python usually allows me to discuss the issue with the community and find out more about the issue and its history. I've also seen other peoples issues discussed, enough times to know that language design is hard. Everyone knows the mechanics it seems, but the devil is in the detail.\r\n\r\n- Paddy."
email: 89f032bea7ea14c8157aaa72a243bd06
